
# Site settings
title: DataWorkbench Styling
email: rolf@data4development.nl
description: Repository with Flatly styling for Jekyll and various tools
brand: DataWorkbench
github: data4development/dataworkbench-jekyll-theme

defaults:
  -
    values:
      layout: "default"

remote_theme: dataworkbench-jekyll-theme
